# Generated by Django 4.2.1 on 2023-05-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_guest',
            new_name='nb_of_guest',
        ),
    ]
